### ISSUE TITLE
my.usa.gov SSL cert issues

### ISSUE THREAD

**Issue by GUI** [GSA/mygov-account#47]
I've run into issues making the omniauth-myusa Ruby client work out of the box due to SSL issues with the my.usa.gov domain. However, it seems like the issue might be wider than just the Ruby client, since I also see similar SSL errors via curl and openssl command line tools (but oddly no issues access the HTTPS site in my browsers). I was able to make omniauth-myusa work by disabling SSL verification, but that obviously isn't ideal. Has something maybe changed with the SSL setup on my.usa.gov?

Here's a basic curl test that is unable to connect over HTTPS:

``` sh
$ curl -v "https://my.usa.gov/"
...
* Peer's certificate issuer is not recognized: 'CN=Go Daddy Secure Certificate Authority - G2,OU=http://certs.godaddy.com/repository/,O="GoDaddy.com, Inc.",L=Scottsdale,ST=Arizona,C=US'
* NSS error -8179
* Closing connection #0
* Peer certificate cannot be authenticated with known CA certificates
curl: (60) Peer certificate cannot be authenticated with known CA certificates
…
```

Even when pointing curl at a fresh CA cert bundle from [curl.haxx.se](http://curl.haxx.se/docs/caextract.html), I get the same errors.

A similar OpenSSL test also reports errors:

``` sh
$ openssl s_client -connect my.usa.gov:443 -showcerts
CONNECTED(00000003)
depth=0 OU = Domain Control Validated, CN = *.usa.gov
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 OU = Domain Control Validated, CN = *.usa.gov
verify error:num=27:certificate not trusted
verify return:1
depth=0 OU = Domain Control Validated, CN = *.usa.gov
verify error:num=21:unable to verify the first certificate
verify return:1
…
```

Thanks!

**Comment by polastre** [comment]
Hey @adam-at-mobomo this looks like the problem on mobile too

**Comment by adam-at-mobomo** [comment]
Yes, I figured this out already, and documented it in the Pivotal story #71050234

```
The certificate is not trusted because no issuer chain was provided.
(Error code: sec_error_unknown_issuer)
```

I provided a link to a validation site that shows this error:

The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. Learn more about this error:  http://www.sslshopper.com/ssl-certificate-not-trusted-error.html . You can fix this by following GoDaddy's Certificate Installation Instructions for your server platform: https://certs.godaddy.com/InstallationInstructions_alt.go . Pay attention to the parts about Intermediate certificates.

**Comment by NoahKunin** [comment]
Resolved: http://www.sslshopper.com/ssl-checker.html#hostname=my.usa.gov
